name: Lint Code


on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install linting dependencies
        run: pip install flake8 black isort

      - name: Run flake8 (Style & Error Check)
        run: |
          
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run black (Format Check)
        run: black --check .

      - name: Run isort (Import Order Check)
        run: isort --check-only .